# Generated by Django 5.1 on 2024-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoplify_api", "0006_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="product_images"
            ),
        ),
    ]
