# Generated by Django 5.1.4 on 2025-01-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0018_alter_review_rating_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shoplify_api.product')),
            ],
            options={
                'unique_together': {('owner', 'product')},
            },
        ),
    ]
