# Generated by Django 5.1.4 on 2025-01-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0019_favoriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shoplify_api.product'),
        ),
    ]
