# Generated by Django 5.1.4 on 2025-01-11 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0020_favoriteproducts_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproducts',
            options={'verbose_name': 'Favorite Products', 'verbose_name_plural': 'Favorite Products'},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproducts',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
