# Generated by Django 5.1.4 on 2025-01-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0022_alter_favoriteproducts_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
