# Generated by Django 5.1.4 on 2025-03-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0026_alter_cartitem_cart_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'Orders History', 'verbose_name_plural': 'Orders History'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
