# Generated by Django 5.1.4 on 2025-03-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0027_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
