# Generated by Django 5.1.4 on 2025-03-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0028_delete_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Products Images'},
        ),
    ]
