# Generated by Django 5.1.4 on 2025-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0029_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed'), ('D', 'Delivered'), ('CA', 'Cancelled')], default='P', max_length=50),
        ),
    ]
