# Generated by Django 5.1.4 on 2025-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0030_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('F', 'Payment Failed'), ('CA', 'Order Cancelled'), ('P', 'Pending Payment'), ('C', 'Payment Complete'), ('D', 'Order Delivered')], default='P', max_length=50),
        ),
    ]
