# Generated by Django 5.1.4 on 2025-07-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0031_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
