# Generated by Django 5.1.4 on 2025-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0032_rename_title_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PAYMENT_STATUS_FAILED', 'Payment Failed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_STATUS_PENDING', 'Pending Payment'), ('PAYMENT_STATUS_COMPLETE', 'Payment Complete'), ('ORDER_DELIVERED', 'Order Delivered')], default='PAYMENT_STATUS_PENDING', max_length=50),
        ),
    ]
