# Generated by Django 5.1.4 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0035_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
