# Generated by Django 5.1.4 on 2025-08-21 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplify_api', '0036_alter_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter discount as a percentage (0 - 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
