# Generated by Django 5.1 on 2024-08-28 12:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_place_api", "0011_remove_category_icon_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_images"
            ),
        ),
    ]
