# Generated by Django 5.1 on 2024-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_place_api", "0013_alter_product_options_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Complete"),
                    ("F", "Failed"),
                    ("D", "Delivered"),
                ],
                default="P",
                max_length=50,
            ),
        ),
    ]
