# Generated by Django 5.1 on 2024-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place_api', '0003_alter_productimage_image_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='product_images'),
        ),
    ]
