# Generated by Django 5.1 on 2024-08-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place_api', '0004_alter_review_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
