# Generated by Django 5.1 on 2024-08-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_place_api", "0005_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="pending_status",
            new_name="payment_status",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="market_place_api.order",
            ),
        ),
    ]
