# Generated by Django 5.1 on 2024-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place_api', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='product_images'),
        ),
    ]
