# Generated by Django 5.1 on 2024-08-28 11:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_place_api", "0010_alter_productimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_images"
            ),
        ),
    ]
