# Generated by Django 5.1 on 2024-11-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place_api', '0012_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
