# Generated by Django 5.1 on 2024-10-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_otp_user_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
    ]
