# Generated by Django 5.1.4 on 2025-01-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
