# Generated by Django 5.1.4 on 2025-02-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_verified_user_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='email_verified',
        ),
    ]
