# Generated by Django 5.1.4 on 2025-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_verified_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
