# Generated by Django 5.1.4 on 2025-02-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_expiry',
            new_name='password_reset_otp_expiry',
        ),
    ]
