# Generated by Django 5.1.4 on 2025-03-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_password_reset_expiry_user_password_reset_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
