# Generated by Django 5.1.4 on 2025-03-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_profile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
    ]
